services:
  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-15.4}
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION:-7.2.1}
    volumes:
      - redis-data:/data
    expose:
      - 6379
    ports:
      - 6379:6379

  server:
    container_name: server
    build:
      context: ./backoffice
      dockerfile: Dockerfile
      target: server
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - WORKER_MODE=server
      - ADMIN_CORS=${ADMIN_CORS:-http://localhost:3000}
      - AUTH_CORS=${AUTH_CORS:-http://localhost:3000}

  worker:
    container_name: worker
    build:
      context: ./backoffice
      dockerfile: Dockerfile
      target: server
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - WORKER_MODE=worker

  admin:
    container_name: admin
    build:
      context: ./backoffice
      dockerfile: Dockerfile
      target: admin
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:9000}
        - ADMIN_PATH=${ADMIN_PATH:-/}
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  redis-data: { driver: local }
  postgres-data: { driver: local }
